#!/bin/bash
#

# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/ANIMALS_outputs.csv" --pipeline lexical --category "ANIMALS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/BODY PARTS_outputs.csv" --pipeline lexical --category "BODY PARTS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/FRUITS_outputs.csv" --pipeline lexical --category "FRUITS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/HOBBIES_outputs.csv" --pipeline lexical --category "HOBBIES"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/HOLIDAYS_outputs.csv" --pipeline lexical --category "HOLIDAYS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/HOME APPLIANCES_outputs.csv" --pipeline lexical --category "HOME APPLIANCES"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/LIQUIDS_outputs.csv" --pipeline lexical --category "LIQUIDS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/MEANS OF TRANSPORT_outputs.csv" --pipeline lexical --category "MEANS OF TRANSPORT"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/MEDICAL CONDITIONS_outputs.csv" --pipeline lexical --category "MEDICAL CONDITIONS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/MUSICAL INSTRUMENTS_outputs.csv" --pipeline lexical --category "MUSICAL INSTRUMENTS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/OCCUPATIONS_outputs.csv" --pipeline lexical --category "OCCUPATIONS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/TOOLS_outputs.csv" --pipeline lexical --category "TOOLS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/VEGETABLES_outputs.csv" --pipeline lexical --category "VEGETABLES"

# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/OFFICE SUPPLIES_outputs.csv" --pipeline lexical --category "OFFICE SUPPLIES"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/ACCOMODATIONS_outputs.csv" --pipeline lexical --category "ACCOMODATIONS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/COUNTRIES_outputs.csv" --pipeline lexical --category "COUNTRIES"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/FLOWERS_outputs.csv" --pipeline lexical --category "FLOWERS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/FOODS_outputs.csv" --pipeline lexical --category "FOODS" 
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/FURNITURE_outputs.csv" --pipeline lexical --category "FURNITURE"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/THINGS FOUND IN KITCHENS_outputs.csv" --pipeline lexical --category "THINGS FOUND IN THE KITCHEN"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/NATURAL ENVIRONMENT_outputs.csv" --pipeline lexical --category "NATURAL ENVIRONMENTS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/SPORTS_outputs.csv" --pipeline lexical --category "SPORTS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/NON-FOOD ITEMS FOUND IN SUPERMARKET_outputs.csv" --pipeline lexical --category "NON-FOOD ITEMS FOUND IN SUPERMARKET"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/TECHNOLOGY GADGETS & DEVICES_outputs.csv" --pipeline lexical --category "TECHNOLOGY GADGETS AND DEVICES"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/TOYS_outputs.csv" --pipeline lexical --category "TOYS"
# python run_foraging.py --data "data/fluency_lists/test_hand_corrected/CLOTHING_outputs.csv" --pipeline lexical --category "CLOTHING"


## UNCORRECTED

# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/ANIMALS_outputs.csv" --pipeline lexical --category "ANIMALS"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/BODY PARTS_outputs.csv" --pipeline lexical --category "BODY PARTS"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/FRUITS_outputs.csv" --pipeline lexical --category "FRUITS"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/HOBBIES_outputs.csv" --pipeline lexical --category "HOBBIES"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/HOLIDAYS_outputs.csv" --pipeline lexical --category "HOLIDAYS"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/HOME APPLIANCES_outputs.csv" --pipeline lexical --category "HOME APPLIANCES"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/LIQUIDS_outputs.csv" --pipeline lexical --category "LIQUIDS"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/MEANS OF TRANSPORT_outputs.csv" --pipeline lexical --category "MEANS OF TRANSPORT"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/MEDICAL CONDITIONS_outputs.csv" --pipeline lexical --category "MEDICAL CONDITIONS"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/MUSICAL INSTRUMENTS_outputs.csv" --pipeline lexical --category "MUSICAL INSTRUMENTS"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/OCCUPATIONS_outputs.csv" --pipeline lexical --category "OCCUPATIONS"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/TOOLS_outputs.csv" --pipeline lexical --category "TOOLS"
# python run_foraging.py --data "data/fluency_lists/test_hand_uncorrected/VEGETABLES_outputs.csv" --pipeline lexical --category "VEGETABLES"




# python run_foraging.py --data "data/fluency_lists/test_uncorrected/ANIMALS_outputs.csv" --pipeline lexical --category "ANIMALS"
# python run_foraging.py --data "data/fluency_lists/test_uncorrected/HOME APPLIANCES_outputs.csv" --pipeline lexical --category "HOME APPLIANCES"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/OFFICE SUPPLIES_outputs.csv" --pipeline lexical --category "OFFICE SUPPLIES"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/ACCOMODATIONS_outputs.csv" --pipeline lexical --category "ACCOMODATIONS"
# python run_foraging.py --data "data/fluency_lists/test_uncorrected/BODY PARTS_outputs.csv" --pipeline lexical --category "BODY PARTS"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/COUNTRIES_outputs.csv" --pipeline lexical --category "COUNTRIES"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/FLOWERS_outputs.csv" --pipeline lexical --category "FLOWERS"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/FOODS_outputs.csv" --pipeline lexical --category "FOODS"
# python run_foraging.py --data "data/fluency_lists/test_uncorrected/FRUITS_outputs.csv" --pipeline lexical --category "FRUITS"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/FURNITURE_outputs.csv" --pipeline lexical --category "FURNITURE"
# python run_foraging.py --data "data/fluency_lists/test_uncorrected/HOBBIES_outputs.csv" --pipeline lexical --category "HOBBIES"
# python run_foraging.py --data "data/fluency_lists/test_cunorrected/HOLIDAYS_outputs.csv" --pipeline lexical --category "HOLIDAYS"
# python run_foraging.py --data "data/fluency_lists/test_uncorrected/MUSICAL INSTRUMENTS_outputs.csv" --pipeline lexical --category "MUSICAL INSTRUMENTS"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/THINGS FOUND IN KITCHENS_outputs.csv" --pipeline lexical --category "THINGS FOUND IN THE KITCHEN"
# python run_foraging.py --data "data/fluency_lists/test_uncorrected/LIQUIDS_outputs.csv" --pipeline lexical --category "LIQUIDS"
# python run_foraging.py --data "data/fluency_lists/test_uncorrected/MEDICAL CONDITIONS_outputs.csv" --pipeline lexical --category "MEDICAL CONDITIONS"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/NATURAL ENVIRONMENT_outputs.csv" --pipeline lexical --category "NATURAL ENVIRONMENTS"
# python run_foraging.py --data "data/fluency_lists/test_uncorrected/OCCUPATIONS_outputs.csv" --pipeline lexical --category "OCCUPATIONS"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/SPORTS_outputs.csv" --pipeline lexical --category "SPORTS"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/NON-FOOD ITEMS FOUND IN SUPERMARKET_outputs.csv" --pipeline lexical --category "NON-FOOD ITEMS FOUND IN SUPERMARKET"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/TECHNOLOGY GADGETS & DEVICES_outputs.csv" --pipeline lexical --category "TECHNOLOGY GADGETS AND DEVICES"
# python run_foraging.py --data "data/fluency_lists/test_uncorrected/TOOLS_outputs.csv" --pipeline lexical --category "TOOLS"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/TOYS_outputs.csv" --pipeline lexical --category "TOYS"
# python run_foraging.py --data "data/fluency_lists/test_uncorrected/MEANS OF TRANSPORT_outputs.csv" --pipeline lexical --category "MEANS OF TRANSPORT"
# python run_foraging.py --data "data/fluency_lists/test_uncorrected/VEGETABLES_outputs.csv" --pipeline lexical --category "VEGETABLES"
# # python run_foraging.py --data "data/fluency_lists/test_uncorrected/CLOTHING_outputs.csv" --pipeline lexical --category "CLOTHING"