#!/bin/bash

python run_foraging.py --data "data/fluency_lists/ANIMALS_outputs.csv" --pipeline lexical --category "ANIMALS"
python run_foraging.py --data "data/fluency_lists/HOME APPLIANCES_outputs.csv" --pipeline lexical --category "HOME APPLIANCES"
# python run_foraging.py --data "data/fluency_lists/OFFICE SUPPLIES_outputs.csv" --pipeline lexical --category "OFFICE SUPPLIES"
# python run_foraging.py --data "data/fluency_lists/ACCOMODATION_outputs.csv" --pipeline lexical --category "ACCOMODATIONS"
python run_foraging.py --data "data/fluency_lists/BODY PARTS_outputs.csv" --pipeline lexical --category "BODY PARTS"
# python run_foraging.py --data "data/fluency_lists/COUNTRIES_outputs.csv" --pipeline lexical --category "COUNTRIES"
# python run_foraging.py --data "data/fluency_lists/FLOWERS_outputs.csv" --pipeline lexical --category "FLOWERS"
# python run_foraging.py --data "data/fluency_lists/FOODS_outputs.csv" --pipeline lexical --category "FOODS"
python run_foraging.py --data "data/fluency_lists/FRUITS_outputs.csv" --pipeline lexical --category "FRUITS"
# python run_foraging.py --data "data/fluency_lists/FURNITURE_outputs.csv" --pipeline lexical --category "FURNITURE"
python run_foraging.py --data "data/fluency_lists/HOBBIES_outputs.csv" --pipeline lexical --category "HOBBIES"
python run_foraging.py --data "data/fluency_lists/HOLIDAYS_outputs.csv" --pipeline lexical --category "HOLIDAYS"
python run_foraging.py --data "data/fluency_lists/MUSICAL INSTRUMENTS_outputs.csv" --pipeline lexical --category "MUSICAL INSTRUMENTS"
# python run_foraging.py --data "data/fluency_lists/THINGS FOUND IN THE KITCHEN_outputs.csv" --pipeline lexical --category "THINGS FOUND IN THE KITCHEN"
python run_foraging.py --data "data/fluency_lists/LIQUIDS_outputs.csv" --pipeline lexical --category "LIQUIDS"
python run_foraging.py --data "data/fluency_lists/MEDICAL CONDITIONS_outputs.csv" --pipeline lexical --category "MEDICAL CONDITIONS"
# python run_foraging.py --data "data/fluency_lists/NATURAL ENVIRONMENTS_outputs.csv" --pipeline lexical --category "NATURAL ENVIRONMENTS"
python run_foraging.py --data "data/fluency_lists/OCCUPATIONS_outputs.csv" --pipeline lexical --category "OCCUPATIONS"
# python run_foraging.py --data "data/fluency_lists/SPORTS_outputs.csv" --pipeline lexical --category "SPORTS"
# python run_foraging.py --data "data/fluency_lists/NON-FOOD ITEMS FOUND IN SUPERMARKET_outputs.csv" --pipeline lexical --category "NON-FOOD ITEMS FOUND IN SUPERMARKET"
# python run_foraging.py --data "data/fluency_lists/TECHNOLOGY GADGETS AND DEVICES_outputs.csv" --pipeline lexical --category "TECHNOLOGY GADGETS AND DEVICES"
python run_foraging.py --data "data/fluency_lists/TOOLS_outputs.csv" --pipeline lexical --category "TOOLS"
# python run_foraging.py --data "data/fluency_lists/TOYS_outputs.csv" --pipeline lexical --category "TOYS"
python run_foraging.py --data "data/fluency_lists/MEANS OF TRANSPORT_outputs.csv" --pipeline lexical --category "MEANS OF TRANSPORT"
python run_foraging.py --data "data/fluency_lists/VEGETABLES_outputs.csv" --pipeline lexical --category "VEGETABLES"
# python run_foraging.py --data "data/fluency_listsa/CLOTHING_outputs.csv" --pipeline lexical --category "CLOTHING"